# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0002_auto_20171202_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querym',
            name='query',
            field=models.TextField(default='This is default query'),
        ),
    ]
