# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0003_auto_20171202_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Query.QueryM'),
        ),
    ]
