# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0004_auto_20171202_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='q',
            new_name='qvalue',
        ),
    ]
