# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0005_auto_20171202_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='qvalue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Query.QueryM'),
        ),
    ]
