# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0006_auto_20171202_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querym',
            name='query',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='qvalue',
        ),
        migrations.AddField(
            model_name='questions',
            name='query',
            field=models.TextField(default='mama'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.TextField(default='yo'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(default='hi'),
        ),
    ]
