# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0007_auto_20171202_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueryM',
        ),
    ]
